name: workflow develop and pull request

on:
  push:
    branches: [ "feature**", "bugfix**" ]
permissions:
  contents: write
  pull-requests: write

jobs:
  workflow_angular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instalando node v18.19.0
      uses: actions/setup-node@v3
      with:
        node-version: "18.19.0"
    - name: Instalando dependencias
      run: npm install
    - name: Pruebas unitarias y cobertura de código
      run: |
        # npm ci
        # npm run test:prod

  merge-develop:
    needs: workflow_angular
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(github.event.head_commit.message, 'develop') }}
      - name: Getting branch name for merge
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Merge with develop from ${{ steps.branch-name.outputs.ref_branch }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ steps.branch-name.outputs.ref_branch }}
          target-branch: develop

  create_release_branch:
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    needs: merge-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "k.maldonadod@uniandes.edu.co"
          git config --global user.name "Kevin Maldonado Delgado"
          git checkout -b release/v${{ github.run_number }}
          git push -f -u origin release/v${{ github.run_number }}

  create-pull-request:
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    needs: create_release_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Pull Request to master
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/v${{ github.run_number }}
          destination_branch: master
          pr_title: "release/v${{ github.run_number }} to master"
          pr_body: "Auto-generated pull request for release to master."
